
{'date': 'Mon Jun 25 2018 15:13:08.598 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 11
  batata doce = "https://i.imgur.com/OkdQ390.jpg"
          ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Jun 25 2018 15:13:26.568 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 15
  from _spy.vitollino.main import STYLE, INVENTARIO, Sala
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Jun 25 2018 15:27:29.394 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 51
  cena=_sala.norte, texto="please, help me, fix my name
                                                       ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Mon Jun 25 2018 15:30:17.736 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    kitchen().norte.vai()
NameError: name 'kitchen' is not defined
'''},
{'date': 'Mon Jun 25 2018 15:31:08.902 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    kitchen().norte.vai()
  module <module> line 27
    PRR = _sala = Sala(Principals_room_n,Principals_room_o,Principals_room_l,Principals_room_s, "principal")
NameError: name 'Principals_room_n' is not defined
'''},
{'date': 'Mon Jul 16 2018 21:49:23.222 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    kitchen().norte.vai()
  module <module> line 27
    PRR = _sala = Sala(Principals_room_n,Principals_room_o,Principals_room_l,Principals_room_s, "principal")
NameError: name 'Principals_room_n' is not defined
'''},
{'date': 'Mon Jul 16 2018 22:05:46.37 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    kitchen().norte.vai()
  module <module> line 27
    PRR = _sala = Sala(Principals_room_n,Principals_room_o,Principals_room_l,Principals_room_s, "principal")
NameError: name 'Principals_room_n' is not defined
'''},
{'date': 'Mon Jul 16 2018 22:08:10.784 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 57
    kitchen().norte.vai()
  module <module> line 37
    sweet_potato = Elemento(sweetpotato, tit = "olive oil", drop="sweet potato",
NameError: name 'sweetpotato' is not defined
'''},
{'date': 'Tue Jul 17 2018 02:10:25.455 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 82
    kitchen().norte.vai()
  module <module> line 53
    _sala.sul.meio.vai = vai_geo
NameError: name 'vai_geo' is not defined
'''},
{'date': 'Fri Apr 05 2024 18:46:38.144 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 81
    kitchen().norte.vai()
  module <module> line 54
    grao = Elemento(grao_de_bico, tit = "suction hood", drag=True,
  module naomi.main line 27
    self.img, self.title, self.real, self.alt = img, tit, drop, alt
  module _spy.vitollino.main line 668
    self.elt.style.backgroundImage = "url({})".format(value)
AttributeError: 'Elemento' object has no attribute 'elt'
'''},
{'date': 'Fri Apr 05 2024 18:46:47.188 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 81
    kitchen().norte.vai()
  module <module> line 54
    grao = Elemento(grao_de_bico, tit = "suction hood", drag=True,
  module naomi.main line 27
    self.img, self.title, self.real, self.alt = img, tit, drop, alt
  module _spy.vitollino.main line 668
    self.elt.style.backgroundImage = "url({})".format(value)
AttributeError: 'Elemento' object has no attribute 'elt'
'''},